//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XinguanSys.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ReportDetails
    {
        [Display(Name ="地区编号")]
        public int AreaID { get; set; }
        [Display(Name = "地区名称")]
        public string AreaName { get; set; }
        [Display(Name = "现有确诊")]
        public int CurrentNum { get; set; }
        [Display(Name = "累计确诊")]
        public int DiagnosisNum { get; set; }
        [Display(Name = "累计治愈")]
        public int CureNum { get; set; }
        [Display(Name = "累计死亡")]
        public int DeathNum { get; set; }
        [Display(Name = "更新时间")]
        public System.DateTime UpdateTime { get; set; }
        [Display(Name = "疫情地图")]
        public string Image { get; set; }
    }
}
